from __future__ import annotations

PAGE_VERSION = "8.2C"

# PHASE_82C_DECISION_CENTER_UI
HTML_TEMPLATE = r'''<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>投递决策中心</title>
  <style>
    :root{--bg:#f3f8f7;--panel:#fff;--text:#14282d;--muted:#687d82;--border:#d7e6e4;--primary:#0f766e;--primary-dark:#075e57;--primary-soft:#e4f5f2;--blue:#2b6cb0;--blue-soft:#eaf2fb;--amber:#9a6700;--amber-soft:#fff3cd;--red:#b23b3b;--red-soft:#fdeaea;--gray-soft:#eef3f3;--shadow:0 14px 38px rgba(18,55,62,.10)}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--text);background:radial-gradient(circle at 8% 0%,rgba(36,170,148,.13),transparent 31%),var(--bg);font-family:Inter,"PingFang SC","Microsoft YaHei",system-ui,sans-serif}button,input,select{font:inherit}button{cursor:pointer}a{color:inherit}
    .shell{width:min(1520px,calc(100% - 28px));margin:auto;padding:18px 0 72px}.top{position:sticky;top:10px;z-index:40;display:flex;justify-content:space-between;align-items:center;gap:16px;padding:15px 17px;border:1px solid var(--border);border-radius:17px;background:rgba(255,255,255,.94);box-shadow:var(--shadow);backdrop-filter:blur(14px)}h1{margin:0;font-size:22px}.sub{margin:4px 0 0;color:var(--muted);font-size:11px}.actions,.inline,.tabs,.chips{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
    .btn{min-height:38px;border:1px solid var(--border);border-radius:10px;padding:8px 12px;color:#344c51;background:#fff;text-decoration:none;font-size:12px;font-weight:750}.btn:hover{border-color:#8fcac3;background:#f6fbfa}.btn.primary{color:#fff;background:var(--primary);border-color:var(--primary)}.btn.danger{color:var(--red);border-color:#efbcbc}.btn.small{min-height:32px;padding:5px 9px;font-size:11px}.btn:disabled{opacity:.52;cursor:not-allowed}.dot{display:inline-block;width:8px;height:8px;margin-right:6px;border-radius:50%;background:#aab8bb}.dot.online{background:#16a394;box-shadow:0 0 0 4px rgba(22,163,148,.12)}.dot.offline{background:#d45d5d}
    .select,.input{min-height:39px;border:1px solid #cbdedb;border-radius:10px;padding:8px 10px;color:var(--text);background:#fff}.select:focus,.input:focus{outline:none;border-color:#5fb8ad;box-shadow:0 0 0 3px rgba(15,118,110,.11)}
    .pair{display:none;margin:15px 0;padding:17px;border:1px solid #ecd99a;border-radius:15px;background:#fffaf0}.pair.show{display:grid;grid-template-columns:1fr minmax(300px,520px);gap:18px;align-items:center}.pair h2{margin:0;font-size:16px}.pair p{margin:7px 0 0;color:#725f29;font-size:11px;line-height:1.65}.pair-controls{display:grid;grid-template-columns:1fr auto;gap:8px}
    .hero{display:grid;grid-template-columns:repeat(6,minmax(120px,1fr));gap:11px;margin:15px 0}.metric{padding:15px;border:1px solid var(--border);border-radius:15px;background:#fff;box-shadow:0 5px 16px rgba(18,55,62,.045)}.metric span{color:var(--muted);font-size:10px}.metric strong{display:block;margin-top:8px;font-size:27px;font-variant-numeric:tabular-nums}.metric.apply strong{color:var(--primary)}.metric.stretch strong{color:var(--blue)}.metric.prepare strong{color:var(--amber)}.metric.defer strong{color:var(--red)}
    .calibration{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-bottom:13px;padding:12px 15px;border:1px solid var(--border);border-radius:14px;background:rgba(255,255,255,.84)}.calibration p{margin:0;color:var(--muted);font-size:11px;line-height:1.55}.calibration strong{color:var(--text)}
    .panel{padding:15px;border:1px solid var(--border);border-radius:17px;background:#fff}.toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px}.tabs{overflow-x:auto}.tab{flex:none;border:1px solid var(--border);border-radius:999px;padding:7px 11px;background:#fff;color:#53686d;font-size:11px;font-weight:750}.tab.active{color:#fff;background:var(--primary);border-color:var(--primary)}.tab .count{margin-left:5px;opacity:.78}.filters{display:grid;grid-template-columns:minmax(240px,1.5fr) minmax(150px,.65fr) auto;gap:9px;margin-top:11px}.switch{display:flex;align-items:center;gap:7px;min-height:39px;padding:0 10px;border:1px solid var(--border);border-radius:10px;color:#53686d;background:#fbfdfd;font-size:11px;font-weight:700}.switch input{accent-color:var(--primary)}.helper{display:flex;justify-content:space-between;gap:12px;margin-top:9px;color:var(--muted);font-size:10px}
    .grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:14px}.card{display:flex;flex-direction:column;min-height:270px;border:1px solid var(--border);border-radius:16px;background:#fff;box-shadow:0 5px 17px rgba(18,55,62,.05);transition:.15s}.card:hover{transform:translateY(-2px);border-color:#9fd2cc}.card-head{display:grid;grid-template-columns:1fr auto;gap:13px;padding:15px 15px 10px}.title{margin:0;font-size:16px;line-height:1.4}.company{margin:5px 0 0;color:var(--muted);font-size:11px}.score-main{text-align:right}.score-main strong{display:block;color:var(--primary-dark);font-size:31px;line-height:1;font-variant-numeric:tabular-nums}.score-main span{color:var(--muted);font-size:9px}.card-meta{padding:0 15px}.pill{display:inline-flex;min-height:24px;align-items:center;border-radius:999px;padding:4px 8px;color:#53686d;background:var(--gray-soft);font-size:10px;font-weight:700}.pill.apply_now{color:var(--primary-dark);background:var(--primary-soft)}.pill.stretch{color:#245a91;background:var(--blue-soft)}.pill.prepare_first{color:#775400;background:var(--amber-soft)}.pill.defer{color:#8f3030;background:var(--red-soft)}.pill.conflict{color:#8f3030;background:var(--red-soft)}
    .scores{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:11px 15px 0}.score-box{padding:9px 10px;border-radius:10px;background:#f3f8f7}.score-box span{color:var(--muted);font-size:9px}.score-box b{display:block;margin-top:3px;font-size:15px}.card-body{flex:1;padding:10px 15px 13px}.line{margin:0;color:#435a60;font-size:11px;line-height:1.6}.line+.line{margin-top:6px}.line b{color:#223a3f}.gap{color:#87631a}.card-actions{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:10px 14px;border-top:1px solid #e7efee;background:#fbfdfd}.action-text{color:var(--primary-dark);font-size:10px;font-weight:750;line-height:1.45}.empty{grid-column:1/-1;padding:50px 20px;border:1px dashed #c3d9d6;border-radius:14px;background:rgba(255,255,255,.7);color:var(--muted);text-align:center;font-size:12px;line-height:1.7}
    .drawer-bg{display:none;position:fixed;inset:0;z-index:80;background:rgba(18,31,35,.38);backdrop-filter:blur(3px)}.drawer-bg.show{display:block}.drawer{position:fixed;z-index:90;top:0;right:0;width:min(780px,95vw);height:100vh;display:flex;flex-direction:column;transform:translateX(104%);background:#f7fbfa;border-left:1px solid var(--border);box-shadow:-18px 0 50px rgba(16,42,48,.20);transition:.22s}.drawer.show{transform:translateX(0)}.drawer-head{display:flex;justify-content:space-between;gap:14px;padding:18px 20px 14px;border-bottom:1px solid var(--border);background:#fff}.drawer-head h2{margin:0;font-size:20px}.drawer-head p{margin:5px 0 0;color:var(--muted);font-size:11px}.close{width:36px;height:36px;border:1px solid var(--border);border-radius:10px;background:#fff;font-size:19px}.drawer-body{flex:1;overflow:auto;padding:16px 20px 98px}.detail-hero{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-bottom:13px}.detail-score{padding:13px;border:1px solid var(--border);border-radius:13px;background:#fff}.detail-score span{color:var(--muted);font-size:9px}.detail-score strong{display:block;margin-top:5px;font-size:25px}.section{margin-bottom:13px;padding:15px;border:1px solid var(--border);border-radius:14px;background:#fff}.section h3{margin:0 0 11px;font-size:14px}.section p{margin:0;color:#435a60;font-size:11px;line-height:1.68}.list{display:grid;gap:7px}.item{padding:9px 10px;border-radius:9px;background:#f3f8f7;color:#40565b;font-size:11px;line-height:1.55}.item.good{border-left:3px solid #56aa9f}.item.bad{border-left:3px solid #d36c6c}.bar-list{display:grid;gap:9px}.bar-row{display:grid;grid-template-columns:128px 1fr 35px;gap:8px;align-items:center;font-size:10px}.bar{height:8px;overflow:hidden;border-radius:999px;background:#e8efee}.bar i{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,#0f766e,#42b3a6)}.tag{display:inline-flex;margin:0 6px 6px 0;border-radius:999px;padding:5px 8px;background:#edf5f4;color:#385257;font-size:10px}.tag.gap{background:#fff3cd;color:#775400}.project{padding:10px;border:1px solid #d8e8e5;border-radius:10px;background:#f8fcfb}.project+.project{margin-top:8px}.project b{display:block;font-size:11px}.project span{display:block;margin-top:4px;color:var(--muted);font-size:10px;line-height:1.5}.status-row{display:grid;grid-template-columns:1fr auto;gap:8px}.drawer-foot{position:absolute;right:0;bottom:0;left:0;display:flex;justify-content:space-between;gap:8px;padding:13px 20px;border-top:1px solid var(--border);background:rgba(255,255,255,.97)}
    .toasts{position:fixed;z-index:200;right:18px;bottom:18px;display:grid;gap:8px;width:min(390px,calc(100% - 36px))}.toast{padding:11px 13px;border:1px solid #cfe1df;border-radius:11px;background:#fff;box-shadow:var(--shadow);font-size:11px;line-height:1.5}.toast.error{border-color:#efbbbb;color:#8b3030}.loading{opacity:.55;pointer-events:none}
    @media(max-width:1180px){.hero{grid-template-columns:repeat(3,1fr)}}@media(max-width:830px){.top{align-items:flex-start;flex-direction:column}.grid{grid-template-columns:1fr}.filters{grid-template-columns:1fr 1fr}.filters .input{grid-column:1/-1}.pair.show{grid-template-columns:1fr}.hero{grid-template-columns:repeat(2,1fr)}.calibration{align-items:flex-start;flex-direction:column}}@media(max-width:560px){.shell{width:calc(100% - 18px)}.filters,.detail-hero{grid-template-columns:1fr}.filters .input{grid-column:auto}.pair-controls,.status-row{grid-template-columns:1fr}.bar-row{grid-template-columns:105px 1fr 32px}.top .actions{width:100%}.top .btn{flex:1;text-align:center}}
  </style>
</head>
<body>
<div class="shell">
  <header class="top">
    <div><h1>投递决策中心</h1><p class="sub">Phase __PAGE_VERSION__ · 从岗位匹配解释到实际投递动作</p></div>
    <div class="actions"><span id="conn"><i id="dot" class="dot"></i>未连接</span><select id="strategy" class="select" aria-label="投递策略"></select><a class="btn" href="/profile" target="_blank">个人档案</a><a class="btn" href="/manage" target="_blank">岗位管理</a><a class="btn" href="/dashboard" target="_blank">分析看板</a><button id="recalculate" class="btn primary">重新计算</button><button id="forget" class="btn danger">重新配对</button></div>
  </header>

  <section id="pair" class="pair"><div><h2>首次使用需要配对本地 API</h2><p>从首次启动设置页复制本地 API 令牌。与岗位管理和个人档案共用同一个浏览器令牌。</p></div><div class="pair-controls"><input id="token" class="input" type="password" placeholder="粘贴本地 API 令牌"><button id="save-token" class="btn primary">保存并连接</button></div></section>

  <section class="hero">
    <article class="metric"><span>待决策岗位</span><strong id="m-queue">—</strong></article>
    <article class="metric apply"><span>立即投递</span><strong id="m-apply">—</strong></article>
    <article class="metric stretch"><span>值得冲刺</span><strong id="m-stretch">—</strong></article>
    <article class="metric prepare"><span>补材料后投递</span><strong id="m-prepare">—</strong></article>
    <article class="metric defer"><span>暂缓</span><strong id="m-defer">—</strong></article>
    <article class="metric"><span>硬条件冲突</span><strong id="m-conflict">—</strong></article>
  </section>

  <section id="calibration" class="calibration"><p>正在读取人工校准结果……</p></section>

  <section id="main-panel" class="panel">
    <div class="toolbar"><div id="tabs" class="tabs"></div><span id="result-count" class="sub">—</span></div>
    <div class="filters"><input id="keyword" class="input" type="search" placeholder="搜索岗位、公司、城市、技能缺口"><select id="sort" class="select"><option value="priority">按投递优先级</option><option value="match">按岗位匹配度</option><option value="opportunity">按机会价值</option></select><label class="switch"><input id="pending-only" type="checkbox" checked>只看待投递队列</label></div>
    <div class="helper"><span>分数来自透明规则和项目证据，不代表Offer概率。</span><span id="run-info">—</span></div>
    <div id="grid" class="grid"><div class="empty">请先完成本地 API 配对。</div></div>
  </section>
</div>

<div id="drawer-bg" class="drawer-bg"></div>
<aside id="drawer" class="drawer" aria-hidden="true">
  <header class="drawer-head"><div><h2 id="drawer-title">岗位详情</h2><p id="drawer-sub">—</p></div><button id="close" class="close" aria-label="关闭">×</button></header>
  <main id="drawer-body" class="drawer-body"></main>
  <footer class="drawer-foot"><div class="inline"><a id="source" class="btn" href="#" target="_blank" rel="noopener">打开原始岗位</a><a class="btn" href="/manage" target="_blank">完整管理</a></div><button id="quick-apply" class="btn primary">标记已投递</button></footer>
</aside>
<div id="toasts" class="toasts"></div>

<script>
(()=>{'use strict';
const TOKEN_KEY='jobMarketApiTokenV1',STRATEGY_KEY='jobDecisionStrategyV1',BASE=location.origin;
const ACTIONS={all:'全部',apply_now:'立即投递',stretch:'值得冲刺',prepare_first:'补材料后投递',defer:'暂缓'};
const STATUS={to_review:'待判断',interested:'感兴趣',preparing:'准备投递',applied:'已投递',written_test:'笔试',interview:'面试',offer:'Offer',rejected:'被拒',abandoned:'放弃'};
const COMPONENTS={skill_fit:'技能匹配',project_evidence:'项目证据',domain_project_match:'领域项目匹配',direction_fit:'方向一致性',feasibility:'现实可行性',salary_relative:'薪资相对位置',growth_value:'成长价值',role_clarity:'职责清晰度',listing_confidence:'招聘状态可信度',urgency:'紧迫度',preference:'个人偏好',preparation_cost:'准备成本',uncertainty:'信息不确定性'};
const s={token:localStorage.getItem(TOKEN_KEY)||'',strategy:localStorage.getItem(STRATEGY_KEY)||'balanced',tab:'all',summary:null,jobs:[],calibration:null,current:null,options:null,pendingOnly:true,keyword:'',sort:'priority'};
const $=id=>document.getElementById(id);const e={pair:$('pair'),token:$('token'),saveToken:$('save-token'),forget:$('forget'),conn:$('conn'),dot:$('dot'),strategy:$('strategy'),recalculate:$('recalculate'),mq:$('m-queue'),ma:$('m-apply'),ms:$('m-stretch'),mp:$('m-prepare'),md:$('m-defer'),mc:$('m-conflict'),calibration:$('calibration'),tabs:$('tabs'),keyword:$('keyword'),sort:$('sort'),pendingOnly:$('pending-only'),resultCount:$('result-count'),runInfo:$('run-info'),grid:$('grid'),panel:$('main-panel'),drawerBg:$('drawer-bg'),drawer:$('drawer'),drawerTitle:$('drawer-title'),drawerSub:$('drawer-sub'),drawerBody:$('drawer-body'),close:$('close'),source:$('source'),quickApply:$('quick-apply'),toasts:$('toasts')};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function toast(message,bad=false){const n=document.createElement('div');n.className='toast'+(bad?' error':'');n.textContent=message;e.toasts.append(n);setTimeout(()=>n.remove(),3800)}
function connection(ok,text){e.dot.className='dot '+(ok?'online':'offline');e.conn.lastChild.textContent=' '+text}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(s.token)headers['X-Job-Market-Token']=s.token;const response=await fetch(BASE+path,{...options,headers,cache:'no-store'});let data={};try{data=await response.json()}catch{}if(!response.ok){if(response.status===401){e.pair.classList.add('show');connection(false,'待配对')}throw new Error(data.detail||('HTTP '+response.status))}return data}
function pct(v){return v==null?'—':Math.round(Number(v)*100)+'%'}
function fmtTime(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)}
function renderStrategies(){const list=s.options?.strategies||[];if(list.length)e.strategy.innerHTML=list.map(x=>`<option value="${esc(x.value)}">${esc(x.label)}策略</option>`).join('');e.strategy.value=s.strategy}
function renderSummary(){const x=s.summary;if(!x){[e.mq,e.ma,e.ms,e.mp,e.md,e.mc].forEach(n=>n.textContent='—');return}e.mq.textContent=x.queue_count;e.ma.textContent=x.by_action_group.apply_now||0;e.ms.textContent=x.by_action_group.stretch||0;e.mp.textContent=x.by_action_group.prepare_first||0;e.md.textContent=x.by_action_group.defer||0;e.mc.textContent=x.hard_conflict_count||0;e.runInfo.textContent=`${esc(x.strategy_label)}策略 · 引擎 ${esc(x.run.engine_version)} · ${fmtTime(x.run.created_at)}`}
function renderCalibration(){const c=s.calibration;if(!c){e.calibration.innerHTML='<p>尚未读取校准结果。</p>';return}if(!c.label_count){e.calibration.innerHTML='<p><strong>尚未完成人工校准。</strong> 先在校准页面标注代表岗位，再判断规则引擎是否合理。</p><a class="btn small" href="/calibrate" target="_blank">打开校准页</a>';return}e.calibration.innerHTML=`<p><strong>人工校准 ${esc(c.label_count)} 条：</strong>完全一致 ${pct(c.exact_accuracy)}，相邻一致 ${pct(c.adjacent_accuracy)}，Top 5 重合 ${esc(c.top5_overlap_count)}/5，硬冲突漏判 ${esc(c.hard_conflict_misses)}。</p><a class="btn small" href="/calibrate" target="_blank">查看校准样本</a>`}
function visibleJobs(){let items=[...s.jobs];if(s.tab!=='all')items=items.filter(x=>x.action_group===s.tab);const q=s.keyword.trim().toLowerCase();if(q)items=items.filter(x=>[x.job_title,x.company_name,x.city,x.direction,...(x.skill_gaps||[]),...(x.matched_skills||[])].join(' ').toLowerCase().includes(q));const key=s.sort==='match'?'match_score':s.sort==='opportunity'?'opportunity_score':'priority_score';items.sort((a,b)=>(Number(b[key])||0)-(Number(a[key])||0)||(Number(b.priority_score)||0)-(Number(a.priority_score)||0));return items}
function counts(){const all={all:s.jobs.length,apply_now:0,stretch:0,prepare_first:0,defer:0};s.jobs.forEach(x=>{if(x.action_group in all)all[x.action_group]++});return all}
function renderTabs(){const c=counts();e.tabs.innerHTML=Object.entries(ACTIONS).map(([key,label])=>`<button class="tab${s.tab===key?' active':''}" data-tab="${key}">${label}<span class="count">${c[key]||0}</span></button>`).join('')}
function card(item){const reasons=(item.reasons||[]).slice(0,2);const gaps=(item.skill_gaps||[]).slice(0,3);const hard=(item.hard_conflicts||[]).length;return `<article class="card"><div class="card-head"><div><h2 class="title">${esc(item.job_title||'未命名岗位')}</h2><p class="company">${esc(item.company_name||'公司未知')} · ${esc(item.city||'城市未知')} · ${esc(item.salary||'薪资未披露')}</p></div><div class="score-main"><strong>${esc(item.priority_score)}</strong><span>投递优先级</span></div></div><div class="card-meta chips"><span class="pill ${esc(item.action_group)}">${esc(item.action_group_label)}</span><span class="pill">${esc(item.direction||'方向未识别')}</span>${hard?`<span class="pill conflict">硬冲突 ${hard}</span>`:''}${!item.queue_eligible?`<span class="pill">${esc(STATUS[item.user_status]||item.user_status)}</span>`:''}</div><div class="scores"><div class="score-box"><span>岗位匹配度</span><b>${esc(item.match_score)}</b></div><div class="score-box"><span>机会价值</span><b>${esc(item.opportunity_score)}</b></div></div><div class="card-body">${reasons.length?`<p class="line"><b>推荐依据：</b>${esc(reasons.join('；'))}</p>`:''}${gaps.length?`<p class="line gap"><b>主要缺口：</b>${esc(gaps.join('、'))}</p>`:''}<p class="line"><b>当前建议：</b>${esc(item.suggested_action||item.action_reason||'查看详情')}</p></div><div class="card-actions"><span class="action-text">${esc(item.action_reason||'')}</span><button class="btn small" data-open="${esc(item.job_id)}">查看解释</button></div></article>`}
function renderJobs(){renderTabs();const items=visibleJobs();e.resultCount.textContent=`显示 ${items.length} / ${s.jobs.length} 个岗位`;e.grid.innerHTML=items.length?items.map(card).join(''):'<div class="empty">当前筛选条件下没有岗位。切换行动分组或关闭“只看待投递队列”再试。</div>'}
function bars(components){return Object.entries(components||{}).map(([key,value])=>`<div class="bar-row"><span>${esc(COMPONENTS[key]||key)}</span><div class="bar"><i style="width:${Math.max(0,Math.min(100,Number(value)||0))}%"></i></div><b>${esc(value)}</b></div>`).join('')}
function list(items,cls=''){return (items||[]).length?`<div class="list">${items.map(x=>`<div class="item ${cls}">${esc(typeof x==='string'?x:JSON.stringify(x))}</div>`).join('')}</div>`:'<p>暂无。</p>'}
function tags(items,cls=''){return (items||[]).length?items.map(x=>`<span class="tag ${cls}">${esc(typeof x==='string'?x:(x.skill_name||JSON.stringify(x)))}</span>`).join(''):'<span class="sub">暂无</span>'}
function projects(items){return (items||[]).length?items.map(x=>`<div class="project"><b>${esc(x.project_name||'项目')}</b><span>${esc(x.reason||x.description||x.evidence||'可在简历中重点呈现该项目。')}</span></div>`).join(''):'<p>当前没有识别到直接相关的项目证据。</p>'}
function detailHtml(item){return `<section class="detail-hero"><article class="detail-score"><span>投递优先级</span><strong>${esc(item.priority_score)}</strong></article><article class="detail-score"><span>岗位匹配度</span><strong>${esc(item.match_score)}</strong></article><article class="detail-score"><span>机会价值</span><strong>${esc(item.opportunity_score)}</strong></article></section><section class="section"><h3>行动建议</h3><p><span class="pill ${esc(item.action_group)}">${esc(item.action_group_label)}</span></p><p style="margin-top:9px"><strong>${esc(item.suggested_action||'')}</strong></p><p style="margin-top:7px">${esc(item.action_reason||'')}</p></section><section class="section"><h3>评分组成</h3><div class="bar-list">${bars(item.components)}</div></section><section class="section"><h3>推荐理由</h3>${list(item.reasons,'good')}</section><section class="section"><h3>风险与硬条件</h3>${list(item.risks,'bad')}</section><section class="section"><h3>技能匹配</h3><p><strong>已匹配</strong></p><div style="margin-top:8px">${tags(item.matched_skills)}</div><p style="margin-top:10px"><strong>部分匹配</strong></p><div style="margin-top:8px">${tags(item.partial_skills)}</div><p style="margin-top:10px"><strong>技能缺口</strong></p><div style="margin-top:8px">${tags(item.skill_gaps,'gap')}</div></section><section class="section"><h3>简历项目建议</h3>${projects(item.resume_projects)}</section><section class="section"><h3>求职状态</h3><div class="status-row"><select id="detail-status" class="select">${Object.entries(STATUS).map(([v,l])=>`<option value="${v}"${item.user_status===v?' selected':''}>${l}</option>`).join('')}</select><button id="save-status" class="btn primary">保存状态</button></div><p style="margin-top:8px">状态改为已投递、笔试、面试、Offer、被拒或放弃后，将默认移出待投递队列。</p></section>`}
async function openDetail(id){try{const data=await api('/api/v1/decision/jobs/'+encodeURIComponent(id)+'?strategy='+encodeURIComponent(s.strategy));s.current=data.item;e.drawerTitle.textContent=s.current.job_title||'岗位详情';e.drawerSub.textContent=[s.current.company_name,s.current.city,s.current.salary].filter(Boolean).join(' · ')||'—';e.drawerBody.innerHTML=detailHtml(s.current);e.source.href=s.current.source_url||'#';e.source.style.display=s.current.source_url?'inline-flex':'none';e.quickApply.disabled=s.current.user_status==='applied';e.drawerBg.classList.add('show');e.drawer.classList.add('show');e.drawer.setAttribute('aria-hidden','false');$('#save-status').onclick=()=>saveStatus($('#detail-status').value)}catch(err){toast('读取岗位解释失败：'+err.message,true)}}
function close(){e.drawerBg.classList.remove('show');e.drawer.classList.remove('show');e.drawer.setAttribute('aria-hidden','true');s.current=null}
async function saveStatus(status){if(!s.current)return;try{await api('/api/v1/jobs/'+encodeURIComponent(s.current.job_id)+'/management',{method:'PATCH',body:JSON.stringify({user_status:status})});toast('求职状态已更新为：'+(STATUS[status]||status));close();await refresh(true)}catch(err){toast('状态更新失败：'+err.message,true)}}
async function loadOptions(){s.options=await api('/api/v1/decision/options');if(!(s.options.strategies||[]).some(x=>x.value===s.strategy))s.strategy=s.options.default_strategy||'balanced';renderStrategies()}
async function loadData(){const query='strategy='+encodeURIComponent(s.strategy);const [summary,jobs,calibration]=await Promise.all([api('/api/v1/decision/summary?'+query),api('/api/v1/decision/jobs?'+query+'&pending_only='+String(s.pendingOnly)+'&limit=500'),api('/api/v1/decision/calibration?'+query)]);s.summary=summary;s.jobs=jobs.items||[];s.calibration=calibration;renderSummary();renderCalibration();renderJobs();connection(true,'已连接');e.pair.classList.remove('show')}
async function refresh(recalculate=false){if(!s.token){e.pair.classList.add('show');connection(false,'待配对');return}e.panel.classList.add('loading');e.recalculate.disabled=true;try{if(!s.options)await loadOptions();if(recalculate)await api('/api/v1/decision/recalculate?strategy='+encodeURIComponent(s.strategy),{method:'POST'});await loadData()}catch(err){connection(false,'连接失败');toast('加载失败：'+err.message,true)}finally{e.panel.classList.remove('loading');e.recalculate.disabled=false}}
e.saveToken.onclick=async()=>{const value=e.token.value.trim();if(!value){toast('令牌不能为空。',true);return}s.token=value;localStorage.setItem(TOKEN_KEY,value);try{await api('/api/v1/decision/options');e.token.value='';s.options=null;await refresh(false);toast('本地 API 配对成功。')}catch(err){toast('连接失败：'+err.message,true)}};e.token.onkeydown=x=>{if(x.key==='Enter')e.saveToken.click()};e.forget.onclick=()=>{localStorage.removeItem(TOKEN_KEY);s.token='';s.options=null;s.summary=null;s.jobs=[];renderSummary();renderCalibration();renderJobs();e.pair.classList.add('show');connection(false,'待配对')};e.recalculate.onclick=()=>refresh(true);e.strategy.onchange=()=>{s.strategy=e.strategy.value;localStorage.setItem(STRATEGY_KEY,s.strategy);s.tab='all';refresh(false)};e.tabs.onclick=x=>{const b=x.target.closest('[data-tab]');if(!b)return;s.tab=b.dataset.tab;renderJobs()};let timer;e.keyword.oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{s.keyword=e.keyword.value;renderJobs()},180)};e.sort.onchange=()=>{s.sort=e.sort.value;renderJobs()};e.pendingOnly.onchange=()=>{s.pendingOnly=e.pendingOnly.checked;s.tab='all';refresh(false)};e.grid.onclick=x=>{const b=x.target.closest('[data-open]');if(b)openDetail(b.dataset.open)};e.close.onclick=close;e.drawerBg.onclick=close;e.quickApply.onclick=()=>saveStatus('applied');addEventListener('keydown',x=>{if(x.key==='Escape')close()});renderSummary();renderCalibration();renderTabs();if(!s.token){e.pair.classList.add('show');connection(false,'待配对')}else refresh(false);
})();
</script>
</body>
</html>'''


def render_decision_page() -> str:
    return HTML_TEMPLATE.replace("__PAGE_VERSION__", PAGE_VERSION)
