from __future__ import annotations

PAGE_VERSION = "7B.2"

HTML_TEMPLATE = r'''<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>岗位管理中心</title>
  <style>
    :root{--bg:#f4f8f8;--panel:#fff;--text:#17282c;--muted:#667b80;--border:#d9e7e7;--primary:#0f766e;--primary-soft:#e5f5f2;--warn-soft:#fff3cd;--danger:#b23b3b;--danger-soft:#fde8e8;--shadow:0 12px 36px rgba(18,55,62,.10)}
    *{box-sizing:border-box}body{margin:0;color:var(--text);background:radial-gradient(circle at 8% 0%,rgba(40,170,150,.11),transparent 34%),var(--bg);font-family:Inter,"PingFang SC","Microsoft YaHei",system-ui,sans-serif}button,input,select,textarea{font:inherit}button{cursor:pointer}
    .shell{width:min(1480px,calc(100% - 28px));margin:auto;padding:18px 0 70px}.top{position:sticky;top:10px;z-index:30;display:flex;justify-content:space-between;align-items:center;gap:16px;padding:15px 17px;border:1px solid var(--border);border-radius:17px;background:rgba(255,255,255,.94);box-shadow:var(--shadow);backdrop-filter:blur(14px)}
    h1{margin:0;font-size:21px}.sub{margin:4px 0 0;color:var(--muted);font-size:11px}.actions,.tags,.tabs{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.btn{min-height:37px;border:1px solid var(--border);border-radius:10px;padding:7px 12px;color:#33494e;background:#fff;text-decoration:none;font-size:12px;font-weight:700}.btn:hover{border-color:#9fd2cc;background:#f5fbfa}.btn.primary{color:#fff;background:var(--primary);border-color:var(--primary)}.btn.danger{color:var(--danger);border-color:#efbaba}.btn.small{min-height:31px;padding:5px 9px;font-size:11px}.btn:disabled{opacity:.5;cursor:not-allowed}
    .pair{display:none;margin:15px 0;padding:17px;border:1px solid #ecd99a;border-radius:15px;background:#fffaf0}.pair.show{display:grid;grid-template-columns:1fr minmax(300px,520px);gap:18px;align-items:center}.pair h2{margin:0;font-size:16px}.pair p{margin:7px 0 0;color:#725f29;font-size:11px;line-height:1.65}.pair-controls{display:grid;grid-template-columns:1fr auto;gap:8px}
    .input,.select,.textarea{width:100%;border:1px solid #ccdddd;border-radius:10px;background:#fff;color:var(--text)}.input,.select{min-height:39px;padding:8px 10px}.textarea{min-height:112px;padding:10px;resize:vertical;line-height:1.55}.input:focus,.select:focus,.textarea:focus{outline:none;border-color:#65bbb0;box-shadow:0 0 0 3px rgba(15,118,110,.11)}
    .summary{display:grid;grid-template-columns:repeat(5,minmax(130px,1fr));gap:11px;margin:15px 0}.metric{padding:15px;border:1px solid var(--border);border-radius:14px;background:#fff;box-shadow:0 5px 16px rgba(18,55,62,.045)}.metric span{color:var(--muted);font-size:11px}.metric strong{display:block;margin-top:8px;font-size:27px;font-variant-numeric:tabular-nums}
    .panel{padding:15px;border:1px solid var(--border);border-radius:16px;background:#fff}.tabs{overflow-x:auto;padding-bottom:8px}.tab{flex:none;border:1px solid var(--border);border-radius:999px;padding:7px 11px;background:#fff;color:#53686d;font-size:11px;font-weight:700}.tab.active{color:#fff;background:var(--primary);border-color:var(--primary)}
    .filters{display:grid;grid-template-columns:minmax(220px,1.5fr) repeat(4,minmax(125px,.8fr)) auto;gap:8px;margin-top:9px}.helper{display:flex;justify-content:space-between;gap:12px;margin-top:9px;color:var(--muted);font-size:10px}.bulk{display:none;position:sticky;top:87px;z-index:20;align-items:center;gap:8px;margin-top:11px;padding:10px;border:1px solid #a9d7d2;border-radius:12px;background:rgba(235,249,247,.97);box-shadow:0 8px 20px rgba(15,118,110,.10)}.bulk.show{display:flex}.bulk strong{min-width:76px;color:#075e57;font-size:11px}
    .grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:14px}.card{display:flex;flex-direction:column;min-height:215px;border:1px solid var(--border);border-radius:15px;background:#fff;box-shadow:0 5px 16px rgba(18,55,62,.05);transition:.15s}.card:hover{transform:translateY(-2px);border-color:#add6d1}.card.selected{border-color:var(--primary);box-shadow:0 0 0 3px rgba(15,118,110,.11)}.card.archived{opacity:.7}
    .card-head{display:flex;gap:10px;padding:15px 15px 9px}.check{width:17px;height:17px;margin-top:3px;accent-color:var(--primary)}.title{margin:0;font-size:16px;line-height:1.4}.company{margin:4px 0 0;color:var(--muted);font-size:11px}.card-body{flex:1;padding:0 15px 12px 42px}.pill{display:inline-flex;min-height:24px;align-items:center;border-radius:999px;padding:4px 8px;color:#53686d;background:#edf4f4;font-size:10px;font-weight:650}.pill.primary{color:#075e57;background:var(--primary-soft)}.pill.warn{color:#775400;background:var(--warn-soft)}.pill.danger{color:#922f2f;background:var(--danger-soft)}.notes{margin:10px 0 0;color:#6f8287;font-size:11px;line-height:1.55;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.card-actions{display:flex;justify-content:flex-end;gap:7px;padding:10px 14px;border-top:1px solid #e8f0f0;background:#fbfdfd}.empty{grid-column:1/-1;padding:48px 20px;border:1px dashed #c7dddd;border-radius:14px;background:rgba(255,255,255,.7);color:var(--muted);text-align:center;font-size:12px;line-height:1.65}
    .drawer-bg{display:none;position:fixed;inset:0;z-index:80;background:rgba(18,31,35,.38);backdrop-filter:blur(3px)}.drawer-bg.show{display:block}.drawer{position:fixed;z-index:90;top:0;right:0;width:min(720px,94vw);height:100vh;display:flex;flex-direction:column;transform:translateX(104%);background:#f8fbfb;border-left:1px solid var(--border);box-shadow:-18px 0 50px rgba(16,42,48,.20);transition:.22s}.drawer.show{transform:translateX(0)}.drawer-head{display:flex;justify-content:space-between;gap:14px;padding:18px 20px 14px;border-bottom:1px solid var(--border);background:#fff}.drawer-head h2{margin:0;font-size:20px}.drawer-head p{margin:5px 0 0;color:var(--muted);font-size:11px}.close{width:35px;height:35px;border:1px solid var(--border);border-radius:10px;background:#fff;font-size:19px}.drawer-body{flex:1;overflow:auto;padding:16px 20px 86px}.section{margin-bottom:13px;padding:15px;border:1px solid var(--border);border-radius:14px;background:#fff}.section h3{margin:0 0 12px;font-size:14px}.form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.field{display:grid;gap:5px}.field.full{grid-column:1/-1}.field label{color:#53686d;font-size:10px;font-weight:750}.help{color:#87979b;font-size:9px;line-height:1.45}.details{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.detail{padding:9px 10px;border-radius:9px;background:#f3f8f7}.detail b{display:block;color:#7c8f93;font-size:9px}.detail span{display:block;margin-top:4px;overflow-wrap:anywhere;font-size:11px;line-height:1.45}.desc{max-height:330px;overflow:auto;padding:12px;border-radius:10px;background:#f3f8f7;white-space:pre-wrap;font-size:11px;line-height:1.7}.history{display:grid;gap:7px}.event{padding:9px 10px;border-left:3px solid #a7d6d0;border-radius:0 9px 9px 0;background:#f4f9f8;font-size:10px;line-height:1.5}.drawer-foot{position:absolute;right:0;bottom:0;left:0;display:flex;justify-content:flex-end;gap:8px;padding:13px 20px;border-top:1px solid var(--border);background:rgba(255,255,255,.96)}
    .toasts{position:fixed;z-index:200;right:18px;bottom:18px;display:grid;gap:8px;width:min(370px,calc(100% - 36px))}.toast{padding:11px 13px;border:1px solid #cfe1df;border-radius:11px;background:#fff;box-shadow:var(--shadow);font-size:11px;line-height:1.5}.toast.error{border-color:#efbbbb;color:#8b3030}.dot{display:inline-block;width:8px;height:8px;margin-right:6px;border-radius:50%;background:#aab8bb}.dot.online{background:#16a394;box-shadow:0 0 0 4px rgba(22,163,148,.12)}.dot.offline{background:#d45d5d}
    @media(max-width:1100px){.summary{grid-template-columns:repeat(3,1fr)}.filters{grid-template-columns:repeat(3,1fr)}.filters .keyword{grid-column:span 2}}@media(max-width:760px){.top{align-items:flex-start;flex-direction:column}.pair.show{grid-template-columns:1fr}.grid{grid-template-columns:1fr}.summary{grid-template-columns:repeat(2,1fr)}.filters{grid-template-columns:1fr 1fr}.filters .keyword{grid-column:1/-1}.bulk{top:145px;flex-wrap:wrap}}@media(max-width:520px){.shell{width:calc(100% - 18px)}.filters,.form,.details{grid-template-columns:1fr}.filters .keyword{grid-column:auto}.pair-controls{grid-template-columns:1fr}.card-body{padding-left:15px}}
  </style>
</head>
<body>
<div class="shell">
  <header class="top"><div><h1>岗位管理中心</h1><p class="sub">Phase __PAGE_VERSION__ · 分类、求职进度、归档与状态历史</p></div><div class="actions"><span id="conn"><i id="dot" class="dot"></i>未连接</span><a class="btn" href="/dashboard" target="_blank">分析看板</a><button id="refresh" class="btn">刷新</button><button id="forget" class="btn danger">重新配对</button></div></header>
  <section id="pair" class="pair"><div><h2>首次使用需要配对本地 API</h2><p>从首次启动设置页复制本地 API 令牌。令牌只保存在当前浏览器的 localStorage。</p></div><div class="pair-controls"><input id="token" class="input" type="password" placeholder="粘贴本地 API 令牌"><button id="save-token" class="btn primary">保存并连接</button></div></section>
  <section class="summary"><article class="metric"><span>全部岗位</span><strong id="m-total">—</strong></article><article class="metric"><span>未归档</span><strong id="m-active">—</strong></article><article class="metric"><span>感兴趣</span><strong id="m-interested">—</strong></article><article class="metric"><span>已投递</span><strong id="m-applied">—</strong></article><article class="metric"><span>已归档</span><strong id="m-archived">—</strong></article></section>
  <section class="panel">
    <div id="tabs" class="tabs"></div>
    <div class="filters"><input id="keyword" class="input keyword" type="search" placeholder="搜索岗位、公司、城市、备注"><input id="city" class="input" placeholder="城市"><select id="listing" class="select"><option value="">全部招聘状态</option><option value="unknown">状态未知</option><option value="active">招聘中</option><option value="suspected_inactive">疑似失效</option><option value="closed">已下线</option></select><select id="quality" class="select"><option value="">全部分析口径</option><option value="auto">自动</option><option value="include">纳入</option><option value="review">需要复核</option><option value="exclude">排除统计</option></select><select id="archive" class="select"><option value="active">未归档</option><option value="archived">仅归档</option><option value="all">全部</option></select><button id="reset" class="btn">清空筛选</button></div>
    <div class="helper"><span>当前显示 <b id="visible">0</b> 条</span><span>排除统计会在下一次分析导出时生效；人工分类本阶段用于管理筛选。</span></div>
    <div id="bulk-management" class="bulk"><strong id="bulk-count">已选0条</strong><select id="bulk-action" class="select"><option value="">选择批量操作</option><optgroup label="个人进度"><option value="user_status:to_review">待判断</option><option value="user_status:interested">感兴趣</option><option value="user_status:preparing">准备投递</option><option value="user_status:applied">已投递</option><option value="user_status:written_test">笔试</option><option value="user_status:interview">面试</option><option value="user_status:offer">Offer</option><option value="user_status:rejected">被拒</option><option value="user_status:abandoned">放弃</option></optgroup><optgroup label="招聘状态"><option value="listing_status:active">招聘中</option><option value="listing_status:suspected_inactive">疑似失效</option><option value="listing_status:closed">已下线</option><option value="listing_status:unknown">状态未知</option></optgroup><optgroup label="分析口径"><option value="quality_override:auto">恢复自动</option><option value="quality_override:include">纳入</option><option value="quality_override:review">复核</option><option value="quality_override:exclude">排除统计</option></optgroup><optgroup label="归档"><option value="archived:true">归档</option><option value="archived:false">恢复归档</option></optgroup></select><button id="apply-bulk" class="btn primary small">应用</button><button id="clear-selected" class="btn small">取消选择</button></div>
  </section>
  <section id="grid" class="grid"><div class="empty">正在连接本地数据库……</div></section>
</div>
<div id="drawer-bg" class="drawer-bg"></div><aside id="drawer" class="drawer" aria-hidden="true"><header class="drawer-head"><div><h2 id="drawer-title">岗位详情</h2><p id="drawer-sub">—</p></div><button id="close" class="close">×</button></header><div id="drawer-body" class="drawer-body"></div><footer class="drawer-foot"><a id="source" class="btn" href="#" target="_blank">原岗位</a><button id="archive-job" class="btn">归档</button><button id="save-job" class="btn primary">保存修改</button></footer></aside><div id="toasts" class="toasts"></div>
<datalist id="category-list"><option value="数据分析与BI"><option value="AI与大模型开发"><option value="机器学习与算法"><option value="数据处理与标注"><option value="数据工程与平台"><option value="AI产品与项目"><option value="数据采集与测试"><option value="其他"></datalist>
<script>
(()=>{'use strict';const TOKEN_KEY='jobMarketApiTokenV1',BASE=location.origin,LIMIT=500;const U={to_review:'待判断',interested:'感兴趣',preparing:'准备投递',applied:'已投递',written_test:'笔试',interview:'面试',offer:'Offer',rejected:'被拒',abandoned:'放弃'};const L={unknown:'状态未知',active:'招聘中',suspected_inactive:'疑似失效',closed:'已下线'};const Q={auto:'自动口径',include:'纳入',review:'需要复核',exclude:'排除统计'};const s={token:localStorage.getItem(TOKEN_KEY)||'',tab:'all',summary:null,jobs:[],selected:new Set(),record:null,dbJobCount:null,autoRefreshBusy:false};const $=id=>document.getElementById(id);const e={pair:$('pair'),token:$('token'),saveToken:$('save-token'),forget:$('forget'),refresh:$('refresh'),conn:$('conn'),dot:$('dot'),mt:$('m-total'),ma:$('m-active'),mi:$('m-interested'),map:$('m-applied'),mar:$('m-archived'),tabs:$('tabs'),keyword:$('keyword'),city:$('city'),listing:$('listing'),quality:$('quality'),archive:$('archive'),reset:$('reset'),visible:$('visible'),bulk:$('bulk-management'),bulkCount:$('bulk-count'),bulkAction:$('bulk-action'),applyBulk:$('apply-bulk'),clearSelected:$('clear-selected'),grid:$('grid'),drawerBg:$('drawer-bg'),drawer:$('drawer'),drawerTitle:$('drawer-title'),drawerSub:$('drawer-sub'),drawerBody:$('drawer-body'),close:$('close'),source:$('source'),archiveJob:$('archive-job'),saveJob:$('save-job'),toasts:$('toasts')};const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');const fmt=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)};function toast(m,bad=false){const n=document.createElement('div');n.className='toast'+(bad?' error':'');n.textContent=m;e.toasts.append(n);setTimeout(()=>n.remove(),3600)}function conn(ok,text){e.dot.className='dot '+(ok?'online':'offline');e.conn.lastChild.textContent=' '+text}
async function api(path,opt={}){if(!s.token)throw new Error('尚未配置本地 API 令牌。');const h=new Headers(opt.headers||{});h.set('X-Job-Market-Token',s.token);if(opt.body)h.set('Content-Type','application/json');const r=await fetch(BASE+path,{...opt,headers:h,cache:'no-store'});const ct=r.headers.get('content-type')||'';const p=ct.includes('json')?await r.json():await r.text();if(!r.ok)throw new Error(typeof p?.detail==='string'?p.detail:(p?.detail?JSON.stringify(p.detail):String(p)));return p}
function tabs(){const c=s.summary?.by_user_status||{};return[{key:'all',label:'全部',count:s.summary?.active||0},...Object.entries(U).map(([key,label])=>({key,label,count:c[key]||0})),{key:'archived',label:'归档',count:s.summary?.archived||0}]}function renderTabs(){e.tabs.innerHTML=tabs().map(t=>`<button class="tab ${s.tab===t.key?'active':''}" data-tab="${esc(t.key)}">${esc(t.label)} ${t.count}</button>`).join('')}function renderSummary(){const z=s.summary||{},c=z.by_user_status||{};e.mt.textContent=z.total??'—';e.ma.textContent=z.active??'—';e.mi.textContent=c.interested||0;e.map.textContent=c.applied||0;e.mar.textContent=z.archived??'—';renderTabs()}
function query(){const p=new URLSearchParams({limit:String(LIMIT),offset:'0'});const av=s.tab==='archived'?'true':e.archive.value==='archived'?'true':e.archive.value==='all'?null:'false';if(av!==null)p.set('archived',av);if(!['all','archived'].includes(s.tab))p.set('user_status',s.tab);if(e.keyword.value.trim())p.set('keyword',e.keyword.value.trim());if(e.city.value.trim())p.set('city',e.city.value.trim());if(e.listing.value)p.set('listing_status',e.listing.value);if(e.quality.value)p.set('quality_override',e.quality.value);return p.toString()}function pc(type,v){if(type==='quality'&&v==='exclude')return'danger';if((type==='quality'&&v==='review')||(type==='listing'&&['closed','suspected_inactive'].includes(v)))return'warn';if(type==='user'&&['interested','preparing','applied','written_test','interview','offer'].includes(v))return'primary';return''}
function card(j){const sel=s.selected.has(j.job_id),cat=j.category_manual||'自动分类';return`<article class="card ${j.archived?'archived':''} ${sel?'selected':''}"><div class="card-head"><input class="check" type="checkbox" data-select="${esc(j.job_id)}" ${sel?'checked':''}><div><h2 class="title">${esc(j.job_title||'未命名岗位')}</h2><p class="company">${esc(j.company_name||'公司未知')}</p></div></div><div class="card-body"><div class="tags"><span class="pill">${esc(j.city||'城市未知')}</span><span class="pill">${esc(j.salary||'薪资未知')}</span><span class="pill">修订 ${esc(j.revision||1)}</span></div><div class="tags" style="margin-top:8px"><span class="pill ${pc('user',j.user_status)}">${esc(U[j.user_status]||j.user_status)}</span><span class="pill ${pc('listing',j.listing_status)}">${esc(L[j.listing_status]||j.listing_status)}</span><span class="pill ${pc('quality',j.quality_override)}">${esc(Q[j.quality_override]||j.quality_override)}</span><span class="pill">${esc(cat)}</span></div><p class="notes">${esc(j.notes||'暂无个人备注')}</p></div><div class="card-actions"><a class="btn small" href="${esc(j.source_url||'#')}" target="_blank">原岗位</a><button class="btn small" data-open="${esc(j.job_id)}">管理详情</button></div></article>`}function renderJobs(){e.visible.textContent=String(s.jobs.length);e.grid.innerHTML=s.jobs.length?s.jobs.map(card).join(''):'<div class="empty">当前筛选条件下没有岗位。</div>';bulk()}function bulk(){e.bulk.classList.toggle('show',s.selected.size>0);e.bulkCount.textContent=`已选${s.selected.size}条`}async function loadSummary(){s.summary=await api('/api/v1/management/summary');renderSummary()}async function loadJobs(){e.grid.innerHTML='<div class="empty">正在读取岗位管理记录……</div>';const p=await api('/api/v1/jobs?'+query());s.jobs=p.items||[];const ids=new Set(s.jobs.map(x=>x.job_id));s.selected=new Set([...s.selected].filter(x=>ids.has(x)));renderJobs()}async function refresh(){if(!s.token){e.pair.classList.add('show');return}e.refresh.disabled=true;try{await Promise.all([loadSummary(),loadJobs()]);conn(true,'本地 API 已连接');e.pair.classList.remove('show')}catch(err){conn(false,'连接失败');e.pair.classList.add('show');toast('刷新失败：'+err.message,true)}finally{e.refresh.disabled=false}}async function pollManagementChanges(){if(!s.token||document.hidden||s.autoRefreshBusy)return;try{const health=await api('/api/v1/health');const count=Number(health.job_count??0);if(s.dbJobCount===null){s.dbJobCount=count;return}if(count===s.dbJobCount)return;const previous=s.dbJobCount;s.dbJobCount=count;s.autoRefreshBusy=true;await refresh();toast(`检测到岗位库变化：${previous} → ${count}，岗位管理已自动刷新。`)}catch{}finally{s.autoRefreshBusy=false}}
function close(){e.drawer.classList.remove('show');e.drawerBg.classList.remove('show');document.body.style.overflow='';s.record=null}const detail=(k,v)=>`<div class="detail"><b>${esc(k)}</b><span>${esc(v||'—')}</span></div>`;const opts=(map,current)=>Object.entries(map).map(([v,l])=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(l)}</option>`).join('');async function open(jobId){e.drawer.classList.add('show');e.drawerBg.classList.add('show');document.body.style.overflow='hidden';e.drawerBody.innerHTML='<div class="empty">正在读取岗位详情与状态历史……</div>';try{const[r,h]=await Promise.all([api('/api/v1/jobs/'+encodeURIComponent(jobId)),api('/api/v1/jobs/'+encodeURIComponent(jobId)+'/history?limit=100')]);s.record=r;draw(r,h.items||[])}catch(err){toast('读取详情失败：'+err.message,true);close()}}
function draw(r,h){const c=r.canonical||{},m=r.management||{},company=c.company_full_name||c.company_short_name||r.company_name||'公司未知';e.drawerTitle.textContent=c.job_title||r.job_title||'岗位详情';e.drawerSub.textContent=company+' · '+(c.city||r.city||'城市未知');e.source.href=c.source_url||c.final_url||r.source_url||'#';e.archiveJob.textContent=m.archived?'恢复归档':'归档岗位';const skills=Array.isArray(c.skills_v11)?c.skills_v11.join('、'):'';const hist=h.length?h.map(x=>`<div class="event">${esc(fmt(x.changed_at))} · <b>${esc(x.field_name)}</b>：${esc(x.old_value||'空')} → ${esc(x.new_value||'空')}</div>`).join(''):'<div class="empty">暂无状态变化记录。</div>';e.drawerBody.innerHTML=`<section class="section"><h3>管理状态</h3><div class="form"><div class="field"><label>个人求职进度</label><select id="f-user" class="select">${opts(U,m.user_status)}</select></div><div class="field"><label>招聘状态</label><select id="f-listing" class="select">${opts(L,m.listing_status)}</select></div><div class="field"><label>分析口径</label><select id="drawer-quality" class="select">${opts(Q,m.quality_override)}</select><small class="help">排除统计会从下一次分析导出中移除。</small></div><div class="field"><label>人工分类（管理标签）</label><input id="f-category" class="input" list="category-list" maxlength="100" value="${esc(m.category_manual||'')}" placeholder="留空使用自动分类"><small class="help">本阶段用于管理筛选。</small></div><div class="field full"><label>个人备注</label><textarea id="f-notes" class="textarea" maxlength="4000">${esc(m.notes||'')}</textarea></div></div></section><section class="section"><h3>岗位信息</h3><div class="details">${detail('公司全称',c.company_full_name||company)}${detail('薪资',c.salary||r.salary)}${detail('城市',c.city||r.city)}${detail('经验要求',c.experience)}${detail('学历',c.education)}${detail('招聘类型',c.employment_type)}${detail('实习出勤',c.internship_days_per_week)}${detail('实习周期',c.internship_duration)}${detail('公司规模',c.company_size)}${detail('融资阶段',c.financing_stage)}${detail('行业',c.industry)}${detail('自动分类',c.role_category_v11)}${detail('技能标签',skills)}${detail('首次采集',fmt(r.first_seen_at))}${detail('最近更新',fmt(r.updated_at))}${detail('数据库修订',r.revision)}</div></section><section class="section"><h3>职位描述</h3><div class="desc">${esc(c.job_description||c.core_text||'暂无职位描述')}</div></section><section class="section"><h3>状态历史</h3><div class="history">${hist}</div></section>`}
async function save(){if(!s.record)return;e.saveJob.disabled=true;const id=s.record.job_id,patch={user_status:$('f-user').value,listing_status:$('f-listing').value,quality_override:$('drawer-quality').value,category_manual:$('f-category').value.trim(),notes:$('f-notes').value.trim()};try{const r=await api('/api/v1/jobs/'+encodeURIComponent(id)+'/management?run_pipeline=true',{method:'PATCH',body:JSON.stringify(patch)});toast(r.changed?'已保存：'+r.changed_fields.join('、'):'没有字段变化。');if(r.pipeline?.started)toast('分析口径变化，已启动后台分析。');await Promise.all([loadSummary(),loadJobs()]);await open(id)}catch(err){toast('保存失败：'+err.message,true)}finally{e.saveJob.disabled=false}}async function archiveCurrent(){if(!s.record)return;const id=s.record.job_id,arch=Boolean(s.record.management?.archived);e.archiveJob.disabled=true;try{await api('/api/v1/jobs/'+encodeURIComponent(id)+'/management',{method:'PATCH',body:JSON.stringify({archived:!arch})});toast(arch?'岗位已恢复。':'岗位已归档，数据仍保留。');close();await Promise.all([loadSummary(),loadJobs()])}catch(err){toast('归档失败：'+err.message,true)}finally{e.archiveJob.disabled=false}}
function parse(v){const i=v.indexOf(':');if(i<1)return null;const k=v.slice(0,i);let x=v.slice(i+1);if(k==='archived')x=x==='true';return{[k]:x}}async function applyBulk(){const patch=parse(e.bulkAction.value),ids=[...s.selected];if(!patch){toast('请先选择批量操作。');return}e.applyBulk.disabled=true;try{const r=await api('/api/v1/jobs/bulk-management?run_pipeline=true',{method:'POST',body:JSON.stringify({job_ids:ids,patch})});toast(`批量处理完成：成功${r.succeeded}条，变化${r.changed}条。`);if(r.pipeline?.started)toast('分析口径变化，已启动后台分析。');s.selected.clear();e.bulkAction.value='';await Promise.all([loadSummary(),loadJobs()])}catch(err){toast('批量处理失败：'+err.message,true)}finally{e.applyBulk.disabled=false;bulk()}}
let timer;const schedule=()=>{clearTimeout(timer);timer=setTimeout(()=>loadJobs().catch(x=>toast('筛选失败：'+x.message,true)),260)};e.saveToken.onclick=async()=>{const t=e.token.value.trim();if(!t){toast('令牌不能为空。',true);return}s.token=t;localStorage.setItem(TOKEN_KEY,t);try{await api('/api/v1/management/summary');e.token.value='';e.pair.classList.remove('show');s.dbJobCount=null;await refresh();toast('本地 API 配对成功。')}catch(err){toast('连接失败：'+err.message,true)}};e.token.onkeydown=x=>{if(x.key==='Enter')e.saveToken.click()};e.forget.onclick=()=>{localStorage.removeItem(TOKEN_KEY);s.token='';s.jobs=[];s.summary=null;s.dbJobCount=null;s.selected.clear();renderSummary();renderJobs();bulk();e.pair.classList.add('show');conn(false,'待配对')};e.refresh.onclick=()=>refresh();e.tabs.onclick=x=>{const b=x.target.closest('[data-tab]');if(!b)return;s.tab=b.dataset.tab;if(s.tab==='archived')e.archive.value='archived';else if(e.archive.value==='archived')e.archive.value='active';renderTabs();loadJobs().catch(y=>toast(y.message,true))};e.keyword.oninput=schedule;e.city.oninput=schedule;[e.listing,e.quality,e.archive].forEach(x=>x.onchange=()=>{if(x===e.archive&&s.tab==='archived'&&x.value!=='archived'){s.tab='all';renderTabs()}loadJobs().catch(y=>toast(y.message,true))});e.reset.onclick=()=>{e.keyword.value='';e.city.value='';e.listing.value='';e.quality.value='';e.archive.value='active';s.tab='all';s.selected.clear();renderTabs();bulk();loadJobs()};e.grid.onchange=x=>{const b=x.target.closest('[data-select]');if(!b)return;b.checked?s.selected.add(b.dataset.select):s.selected.delete(b.dataset.select);renderJobs()};e.grid.onclick=x=>{const b=x.target.closest('[data-open]');if(b)open(b.dataset.open)};e.clearSelected.onclick=()=>{s.selected.clear();renderJobs()};e.applyBulk.onclick=()=>applyBulk();e.close.onclick=close;e.drawerBg.onclick=close;e.saveJob.onclick=()=>save();e.archiveJob.onclick=()=>archiveCurrent();addEventListener('keydown',x=>{if(x.key==='Escape')close()});document.addEventListener('visibilitychange',()=>{if(!document.hidden)pollManagementChanges()});window.setInterval(pollManagementChanges,2000);renderSummary();renderTabs();bulk();if(!s.token){e.pair.classList.add('show');conn(false,'待配对');e.grid.innerHTML='<div class="empty">请先完成本地 API 配对。</div>'}else refresh()})();
</script>
</body>
</html>'''


def render_management_page() -> str:
    return HTML_TEMPLATE.replace("__PAGE_VERSION__", PAGE_VERSION)
